databases:
  - name: shams-wishes-db
    databaseName: shams_universe
    user: shams_user
    plan: free

services:
  - type: web
    name: little-universe-shams-moni
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: shams-wishes-db
          property: connectionString
